version: '3.8'
services:
  service1:
    image: mishannnny/service1:latest
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
  service2:
    image: mishannnny/service2:latest
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=production