apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  labels:
    app: service2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: mishannnny/service2:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"